In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [4]:
ar=np.array(l)

In [7]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
a = [2,3,4]

In [10]:
np.asanyarray(a)

array([2, 3, 4])

In [11]:
b = np.matrix(l)

In [12]:
b

matrix([[1, 2, 3, 4]])

In [15]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [16]:
c= a

In [17]:
c

[2, 3, 4]

In [18]:
 c[0] = 100

In [19]:
c

[100, 3, 4]

In [20]:
"""Here shallow copy hoga index ki jagah naya aajayega"""

'Here shallow copy hoga index ki jagah naya aajayega'

In [21]:
d = np.copy(a)

In [22]:
d

array([100,   3,   4])

In [23]:
a

[100, 3, 4]

In [24]:
a[1] = 400

In [25]:
a

[100, 400, 4]

In [26]:
d

array([100,   3,   4])

In [27]:
"""naya location me copy hoga d to deep copy hoga isliye """

'naya location me copy hoga d to deep copy hoga isliye '

In [28]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [30]:
"""yaha  par index ka multiplication hoga do side par 0,1,2 aayega and uske according ye hoga"""

'yaha  par index ka multiplication hoga do side par 0,1,2 aayega and uske according ye hoga'

In [31]:
iterable = ( i*i for i in range(5))

In [33]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [35]:
np.fromstring('234 234', sep = ' ')

array([234., 234.])

In [36]:
np.fromstring('4,5' , sep=',')

array([4., 5.])

In [37]:
#numpy = Data Types

In [38]:
l = [2,3,4,5,6]

In [39]:
ar = np.array(l)

In [40]:
ar

array([2, 3, 4, 5, 6])

In [42]:
ar.ndim

1

In [43]:
ar2 = np.array([[1,2,3], [5,6,7]])

In [44]:
ar2

array([[1, 2, 3],
       [5, 6, 7]])

In [46]:
ar2.ndim

2

In [47]:
ar.size

5

In [49]:
ar2.size

6

In [50]:
ar.shape

(5,)

In [51]:
ar2.shape

(2, 3)

In [52]:
"""yaha par pahela vala hamesha row represent karta hain ad baad vala column ko reprsent karta hain"""

'yaha par pahela vala hamesha row represent karta hain ad baad vala column ko reprsent karta hain'

In [53]:
ar.dtype

dtype('int32')

In [54]:
ar2.dtype

dtype('int32')

In [56]:
ar22 = np.array([(1.4,45,45) , (23,34,56)])

In [57]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 34. , 56. ]])

In [58]:
ar22.dtype

dtype('float64')

In [59]:
range(7)

range(0, 7)

In [60]:
list(range(5))

[0, 1, 2, 3, 4]

In [61]:
list(range(0.1, 5))

TypeError: 'float' object cannot be interpreted as an integer

In [62]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [63]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [65]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [66]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [67]:
"""yaha par 1 and 5 ke bich 10 number produce karke dega """

'yaha par 1 and 5 ke bich 10 number produce karke dega '

In [68]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [69]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [71]:
"""yaha par 4*2 matrix banega aur aise 3 banege matrix ya array"""

'yaha par 4*2 matrix banega aur aise 3 banege matrix ya array'

In [72]:
np.zeros((3,4,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [73]:
ar4 = np.zeros((3,4,3,2))

In [75]:
ar4.ndim

4

In [76]:
np.ones(4)

array([1., 1., 1., 1.])

In [78]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [79]:
on = np.ones((2,3,2))

In [81]:
on *4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [82]:
np.empty((3,5))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.30861378e+295]])

In [83]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [84]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [85]:
np.linspace(2,4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [86]:
np.logspace(2,5 ,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [87]:
np.logspace(2,5 ,10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [91]:
arr=np.random.randn(3,4)

In [89]:
import pandas as pd

In [92]:
pd.DataFrame(arr)

          0         1         2         3
0  0.573946 -0.862856 -1.178304 -0.232343
1  0.137885  0.218853 -1.987108  1.426334
2  1.429265  0.223460  0.629102 -0.132071

In [93]:
np.random.rand(3,4)

array([[0.12162159, 0.36313089, 0.55797063, 0.28718344],
       [0.03308563, 0.61890255, 0.09130582, 0.28988845],
       [0.69338285, 0.84998844, 0.54697276, 0.98373962]])

In [94]:
np.random.randint(1,100,(300,400))

array([[58, 30, 26, ..., 26, 78, 39],
       [31,  2, 89, ..., 98, 76, 49],
       [30, 27, 96, ..., 92, 16, 14],
       ...,
       [71, 38, 45, ..., 14, 68,  5],
       [58,  5, 78, ..., 41, 77, 34],
       [29, 62, 57, ...,  7, 72, 24]])

In [95]:
pd.DataFrame(np.random.randint(1,100,(300,400)))

,0,1,2,3,4,5,6,7,8,9,...,390,391,392,393,394,395,396,397,398,399
0,54,10,51,55,43,4,69,21,69,64,...,84,1,54,85,37,30,49,37,24,15
1,30,15,65,88,90,47,35,69,47,53,...,58,29,64,57,93,31,95,27,92,38
2,3,64,78,31,62,54,17,16,10,46,...,24,56,61,29,39,73,32,27,76,88
3,31,49,46,37,24,44,18,40,1,16,...,17,47,82,4,83,63,71,78,75,48
4,51,1,14,84,70,43,42,32,24,81,...,18,38,3,34,93,34,10,41,63,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,11,23,17,33,58,38,44,49,89,81,...,17,76,80,23,68,77,30,57,4,9
296,86,95,13,58,45,30,53,61,28,83,...,42,96,81,11,82,85,74,97,69,77
297,48,41,67,35,87,2,27,96,84,69,...,38,11,87,88,23,1,47,72,91,87
298,90,26,99,36,44,63,42,24,94,96,...,8,15,27,45,92,72,13,63,13,91
299,19,86,43,6,56,79,86,76,32,92,...,54,38,40,57,31,88,75,84,40,93

In [96]:
pd.DataFrame(np.random.randint(1,100,(300,400))).to_csv('create.csv')

In [101]:
"""Yaha par hamne aek data frame create kiya random data ko aur usko csv file banake usme dala aur ye bahut interesting hain"""

'Yaha par hamne aek data frame create kiya random data ko aur usko csv file banake usme dala aur ye bahut interesting hain'

In [97]:
arr = np.random.rand(3,4)

In [98]:
arr

array([[0.72168804, 0.32343978, 0.61071792, 0.73813618],
       [0.91024114, 0.33409239, 0.16481602, 0.24970091],
       [0.94712971, 0.48436597, 0.8023841 , 0.6094206 ]])

In [99]:
arr.reshape(6,2)

array([[0.72168804, 0.32343978],
       [0.61071792, 0.73813618],
       [0.91024114, 0.33409239],
       [0.16481602, 0.24970091],
       [0.94712971, 0.48436597],
       [0.8023841 , 0.6094206 ]])

In [100]:
"""hum yaha par data ko reshape karte hain using reshape function
condition : 1:jo bhi row and column de rahe ho wo total jitne bhi data hain uske multiple me hona chaiye"""

'hum yaha par data ko reshape karte hain using reshape function\ncondition : 1:jo bhi row and column de rahe ho wo total jitne bhi data hain uske multiple me hona chaiye'

In [103]:
arr.reshape(6, -13535523532)

array([[0.72168804, 0.32343978],
       [0.61071792, 0.73813618],
       [0.91024114, 0.33409239],
       [0.16481602, 0.24970091],
       [0.94712971, 0.48436597],
       [0.8023841 , 0.6094206 ]])

In [104]:
"""yaha par koi bhi minus number par hoga kunki use khud pata hain ki arr me total itne data hain """

'yaha par koi bhi minus number par hoga kunki use khud pata hain ki arr me total itne data hain '

In [105]:
arr1 = arr.reshape(6, -13535523532)

In [106]:
arr1

array([[0.72168804, 0.32343978],
       [0.61071792, 0.73813618],
       [0.91024114, 0.33409239],
       [0.16481602, 0.24970091],
       [0.94712971, 0.48436597],
       [0.8023841 , 0.6094206 ]])

In [107]:
arr[1][1]

0.3340923854203821

In [108]:
arr1[2:5][1]

array([0.16481602, 0.24970091])

In [110]:
arr = np.random.randint(1,100,(5,5))

In [111]:
arr

array([[14, 15, 54, 86, 64],
       [53, 87, 60, 17, 28],
       [32, 20, 26, 67, 80],
       [45, 26, 29, 19, 26],
       [18, 39, 47, 86, 97]])

In [112]:
arr[arr>50]

array([54, 86, 64, 53, 87, 60, 67, 80, 86, 97])

In [113]:
arr

array([[14, 15, 54, 86, 64],
       [53, 87, 60, 17, 28],
       [32, 20, 26, 67, 80],
       [45, 26, 29, 19, 26],
       [18, 39, 47, 86, 97]])

In [114]:
arr[2:4 , [1,2]]

array([[20, 26],
       [26, 29]])

In [115]:
""" ye aekka pen aur paper me kar lena tabhi ye samaj me aayega """

' ye aekka pen aur paper me kar lena tabhi ye samaj me aayega '

In [116]:
arr[0][0] = 5000

In [117]:
arr

array([[5000,   15,   54,   86,   64],
       [  53,   87,   60,   17,   28],
       [  32,   20,   26,   67,   80],
       [  45,   26,   29,   19,   26],
       [  18,   39,   47,   86,   97]])

In [119]:
arr4 = np.random.randint(1,3, (3,3))
arr5 = np.random.randint(1,3, (3,3))

In [120]:
arr4

array([[1, 2, 2],
       [1, 1, 1],
       [2, 2, 1]])

In [121]:
arr5

array([[1, 2, 1],
       [2, 1, 2],
       [1, 1, 2]])

In [122]:
arr4 + arr5

array([[2, 4, 3],
       [3, 2, 3],
       [3, 3, 3]])

In [123]:
arr4 *arr5

array([[1, 4, 2],
       [2, 1, 2],
       [2, 2, 2]])

In [124]:
""" yr sirf index wise multiplication hain matrix multiplication nai  hain"""

' yr sirf index wise multiplication hain matrix multiplication nai  hain'

In [125]:
arr4@arr5

array([[7, 6, 9],
       [4, 4, 5],
       [7, 7, 8]])

In [126]:
""" ye hame matrix multi plication karke deta hain"""

' ye hame matrix multi plication karke deta hain'

In [127]:
 arr4/0

C:\Users\Rameshbhai patel\AppData\Local\Temp\ipykernel_12964\2643365544.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0

array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [128]:
arr1 + 100

array([[100.72168804, 100.32343978],
       [100.61071792, 100.73813618],
       [100.91024114, 100.33409239],
       [100.16481602, 100.24970091],
       [100.94712971, 100.48436597],
       [100.8023841 , 100.6094206 ]])

In [129]:
arr4 ** 2

array([[1, 4, 4],
       [1, 1, 1],
       [4, 4, 1]])

In [130]:
 #numpy -Bradcasting

In [132]:
arr6= np.zeros((4,4))

In [133]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [134]:
row = np.array([1,2,3,4])

In [135]:
row

array([1, 2, 3, 4])

In [136]:
arr6 +row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [138]:
row.ndim

1

In [140]:
row.shape

(4,)

In [141]:
row.T

array([1, 2, 3, 4])

In [142]:
col = np.array([[1,2,3,4]])

In [143]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [144]:
col

array([[1, 2, 3, 4]])

In [147]:
col.T + arr6

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [148]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [150]:
arr7 = np.random.randint(1,4,(3,4))

In [151]:
arr7

array([[1, 2, 1, 2],
       [2, 3, 1, 3],
       [3, 3, 2, 1]])

In [152]:
np.sqrt(arr7)

array([[1.        , 1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.73205081, 1.        , 1.73205081],
       [1.73205081, 1.73205081, 1.41421356, 1.        ]])

In [153]:
np.exp(arr1)

array([[2.0579041 , 1.38187293],
       [1.84175315, 2.0920327 ],
       [2.48492168, 1.39667217],
       [1.17917615, 1.28364144],
       [2.57829856, 1.62314556],
       [2.23085317, 1.83936536]])

In [155]:
np.log10(arr7)

array([[0.        , 0.30103   , 0.        , 0.30103   ],
       [0.30103   , 0.47712125, 0.        , 0.47712125],
       [0.47712125, 0.47712125, 0.30103   , 0.        ]])