In [2]:
import pandas as pd

In [3]:
pip install pandas

Requirement already satisfied: pandas in c:\users\rameshbhai patel\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rameshbhai patel\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\rameshbhai patel\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\rameshbhai patel\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\rameshbhai patel\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\rameshbhai patel\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pd.read_csv("annual-enterprise-survey-2021-financial-year-provisional-csv.csv")

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
41710,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41711,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41712,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41713,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41714,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [8]:
df=pd.read_csv("annual-enterprise-survey-2021-financial-year-provisional-csv.csv")

In [9]:
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...

In [10]:
df.tail()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
41710,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41711,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41712,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41713,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41714,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [11]:
df.tail(3)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
41712,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41713,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41714,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [12]:
type(df)

pandas.core.frame.DataFrame

In [13]:
list(df.columns)

['Year',
 'Industry_aggregation_NZSIOC',
 'Industry_code_NZSIOC',
 'Industry_name_NZSIOC',
 'Units',
 'Variable_code',
 'Variable_name',
 'Variable_category',
 'Value',
 'Industry_code_ANZSIC06']

In [14]:
df['Variable_name']

0                                           Total income
1        Sales, government funding, grants and subsidies
2                      Interest, dividends and donations
3                                   Non-operating income
4                                      Total expenditure
                              ...
41710                                        Quick ratio
41711                Margin on sales of goods for resale
41712                                   Return on equity
41713                             Return on total assets
41714                              Liabilities structure
Name: Variable_name, Length: 41715, dtype: object

In [15]:
df['Variable_name']

0                                           Total income
1        Sales, government funding, grants and subsidies
2                      Interest, dividends and donations
3                                   Non-operating income
4                                      Total expenditure
                              ...
41710                                        Quick ratio
41711                Margin on sales of goods for resale
41712                                   Return on equity
41713                             Return on total assets
41714                              Liabilities structure
Name: Variable_name, Length: 41715, dtype: object

In [16]:
df['Year']

0        2021
1        2021
2        2021
3        2021
4        2021
         ...
41710    2013
41711    2013
41712    2013
41713    2013
41714    2013
Name: Year, Length: 41715, dtype: int64

In [17]:
type(df['Value'])

pandas.core.series.Series

In [19]:
list(df['Units'])

['Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars',
 'Dollars',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Percentage',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',
 'Dollars (millions)',

In [22]:
df[['year']]

KeyError: "None of [Index(['year'], dtype='object')] are in the [columns]"

In [23]:
df.columns

Index(['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC',
       'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name',
       'Variable_category', 'Value', 'Industry_code_ANZSIC06'],
      dtype='object')

In [25]:
df[['Industry_aggregation_NZSIOC','Value']]

      Industry_aggregation_NZSIOC    Value
0                         Level 1  757,504
1                         Level 1  674,890
2                         Level 1   49,593
3                         Level 1   33,020
4                         Level 1  654,404
...                           ...      ...
41710                     Level 3       52
41711                     Level 3       40
41712                     Level 3       12
41713                     Level 3        5
41714                     Level 3       46

[41715 rows x 2 columns]

In [26]:
pd.read_excel("")

TypeError: read_excel() missing 1 required positional argument: 'io'