In [27]:
import pandas as pd

In [28]:
data = {"a":[1,2,3,4,5],
       "b":[4,5,56,6,7],
       "c":["kavan","krish","navin","dhynam","keval"]}

In [29]:
data

{'a': [1, 2, 3, 4, 5],
 'b': [4, 5, 56, 6, 7],
 'c': ['kavan', 'krish', 'navin', 'dhynam', 'keval']}

In [30]:
df=pd.DataFrame(data)

In [31]:
df

   a   b       c
0  1   4   kavan
1  2   5   krish
2  3  56   navin
3  4   6  dhynam
4  5   7   keval

In [32]:
df.set_index('a',inplace=True)

In [33]:
df

    b       c
a
1   4   kavan
2   5   krish
3  56   navin
4   6  dhynam
5   7   keval

In [34]:
df.reset_index()

   a   b       c
0  1   4   kavan
1  2   5   krish
2  3  56   navin
3  4   6  dhynam
4  5   7   keval

In [35]:
data = {"a":[1,2,3,4,5],
       "b":[4,5,56,6,7],
       "c":["kavan","krish","navin","dhynam","keval"]}
df1=pd.DataFrame(data,index = ['a','b','c','d','e'])

In [36]:
df1

   a   b       c
a  1   4   kavan
b  2   5   krish
c  3  56   navin
d  4   6  dhynam
e  5   7   keval

In [37]:
df1.reindex(['b','c','d','e','a'])

   a   b       c
b  2   5   krish
c  3  56   navin
d  4   6  dhynam
e  5   7   keval
a  1   4   kavan

In [38]:
df1

   a   b       c
a  1   4   kavan
b  2   5   krish
c  3  56   navin
d  4   6  dhynam
e  5   7   keval

In [39]:
df.iterrows()

In [40]:
for i in df.iterrows():
    print(i)

(1, b        4
c    kavan
Name: 1, dtype: object)
(2, b        5
c    krish
Name: 2, dtype: object)
(3, b       56
c    navin
Name: 3, dtype: object)
(4, b         6
c    dhynam
Name: 4, dtype: object)
(5, b        7
c    keval
Name: 5, dtype: object)

In [41]:
df1

   a   b       c
a  1   4   kavan
b  2   5   krish
c  3  56   navin
d  4   6  dhynam
e  5   7   keval

In [42]:
for i,j in df.iterrows():
    print( j)

b        4
c    kavan
Name: 1, dtype: object
b        5
c    krish
Name: 2, dtype: object
b       56
c    navin
Name: 3, dtype: object
b         6
c    dhynam
Name: 4, dtype: object
b        7
c    keval
Name: 5, dtype: object

In [43]:
df1

   a   b       c
a  1   4   kavan
b  2   5   krish
c  3  56   navin
d  4   6  dhynam
e  5   7   keval

In [44]:
for i  in df1.iteritems():
    print(i)

AttributeError: 'DataFrame' object has no attribute 'iteritems'

In [45]:
 for col_name,column in df1.iteritems():
        print(col_name , column)

AttributeError: 'DataFrame' object has no attribute 'iteritems'

In [47]:
df1

   a   b       c
a  1   4   kavan
b  2   5   krish
c  3  56   navin
d  4   6  dhynam
e  5   7   keval

In [49]:
df1['a']

a    1
b    2
c    3
d    4
e    5
Name: a, dtype: int64

In [50]:
list(df1['a'])

[1, 2, 3, 4, 5]

In [53]:
[ i for i in df1['a']]

[1, 2, 3, 4, 5]

In [54]:
df1

   a   b       c
a  1   4   kavan
b  2   5   krish
c  3  56   navin
d  4   6  dhynam
e  5   7   keval

In [57]:
def test(x):
    return x.sum()
df1.apply(test, axis=0)

a                            15
b                            78
c    kavankrishnavindhynamkeval
dtype: object

In [58]:
df1

   a   b       c
a  1   4   kavan
b  2   5   krish
c  3  56   navin
d  4   6  dhynam
e  5   7   keval

In [60]:
df2 = df1[['a','b']]

In [61]:
df2

   a   b
a  1   4
b  2   5
c  3  56
d  4   6
e  5   7

In [62]:
df2.applymap(lambda x:x**2)

    a     b
a   1    16
b   4    25
c   9  3136
d  16    36
e  25    49

In [63]:
df1

   a   b       c
a  1   4   kavan
b  2   5   krish
c  3  56   navin
d  4   6  dhynam
e  5   7   keval

In [64]:
df

    b       c
a
1   4   kavan
2   5   krish
3  56   navin
4   6  dhynam
5   7   keval

In [65]:
df.sort_values('c')

    b       c
a
4   6  dhynam
1   4   kavan
5   7   keval
2   5   krish
3  56   navin

In [66]:
df.sort_values('b')

    b       c
a
1   4   kavan
2   5   krish
4   6  dhynam
5   7   keval
3  56   navin

In [67]:
df.sort_values('b','c')

TypeError: DataFrame.sort_values() takes 2 positional arguments but 3 were given

In [69]:
df.sort_index(ascending = False)

    b       c
a
5   7   keval
4   6  dhynam
3  56   navin
2   5   krish
1   4   kavan

In [72]:
pd.set_option("display.max_colwidth",500)
df3 =pd.DataFrame({'Desc':["this is Data Science master course for python Devloper . thus Data Science is the most demanding domain for future aspect."]})

In [73]:
df3

                                                                                                                         Desc
0  this is Data Science master course for python Devloper . thus Data Science is the most demanding domain for future aspect.

In [74]:
"""Agar hamare paas bohot sara data hogaya tab wo automatically nai dikhayega hame set option karna padega display ke sath"""

'Agar hamare paas bohot sara data hogaya tab wo automatically nai dikhayega hame set option karna padega display ke sath'

In [75]:
df3

                                                                                                                         Desc
0  this is Data Science master course for python Devloper . thus Data Science is the most demanding domain for future aspect.

In [78]:
pd.set_option("display.max_colwidth",20)
df4=pd.DataFrame({"Intro":["namaskaram! ,i,m Kavan Patel cururently pursuing 4th year B.E in LDRP institute . i'm Java Devloper. My expertise is spring ,sevlet , jdbc. here i'm practice codeing for collage or campus placement . This is not for sure about my capablity because i don't enough code for any suitable position in it company."]})

In [79]:
df4

                 Intro
0  namaskaram! ,i,m...

In [80]:
pd.set_option("display.max_colwidth",500)
df4=pd.DataFrame({"Intro":["namaskaram! ,i,m Kavan Patel cururently pursuing 4th year B.E in LDRP institute . i'm Java Devloper. My expertise is spring ,sevlet , jdbc. here i'm practice codeing for collage or campus placement . This is not for sure about my capablity because i don't enough code for any suitable position in it company."]})

In [81]:
df4

                                                                                                                                                                                                                                                                                                                  Intro
0  namaskaram! ,i,m Kavan Patel cururently pursuing 4th year B.E in LDRP institute . i'm Java Devloper. My expertise is spring ,sevlet , jdbc. here i'm practice codeing for collage or campus placement . This is not for sure about my capablity because i don't enough code for any suitable position in it company.

In [82]:
df4=pd.DataFrame({"Intro":["namaskaram! ,i,m Kavan Patel cururently pursuing 4th year B.E in LDRP institute . i'm Java Devloper. My expertise is spring ,sevlet , jdbc. here i'm practice codeing for collage or campus placement . This is not for sure about my capablity because i don't enough code for any suitable position in it company.","my hobby is do yoga , learning , analysis any thing , think any situation ","My Favourtite color is blue ."]})

In [83]:
df4

                                                                                                                                                                                                                                                                                                                  Intro
0  namaskaram! ,i,m Kavan Patel cururently pursuing 4th year B.E in LDRP institute . i'm Java Devloper. My expertise is spring ,sevlet , jdbc. here i'm practice codeing for collage or campus placement . This is not for sure about my capablity because i don't enough code for any suitable position in it company.
1                                                                                                                                                                                                                                            my hobby is do yoga , learning , analysis any thing , think any situation
2                                                                                                                                                                                                                                                                                         My Favourtite color is blue .

In [92]:
df4['len']=df4['Intro'].apply(len)

In [93]:
df4

,Intro,len
0,"namaskaram! ,i,m Kavan Patel cururently pursuing 4th year B.E in LDRP institute . i'm Java Devloper. My expertise is spring ,sevlet , jdbc. here i'm practice codeing for collage or campus placement . This is not for sure about my capablity because i don't enough code for any suitable position in it company.",308
1,"my hobby is do yoga , learning , analysis any thing , think any situation",74
2,My Favourtite color is blue .,29

In [95]:
t = "i use to tech Data Science"
len(t.split())

6

In [97]:
df4['word_count'] = df4['Intro'].apply(lambda x:len(x.split()))

In [98]:
df4

,Intro,len,word_count
0,"namaskaram! ,i,m Kavan Patel cururently pursuing 4th year B.E in LDRP institute . i'm Java Devloper. My expertise is spring ,sevlet , jdbc. here i'm practice codeing for collage or campus placement . This is not for sure about my capablity because i don't enough code for any suitable position in it company.",308,53
1,"my hobby is do yoga , learning , analysis any thing , think any situation",74,15
2,My Favourtite color is blue .,29,6

In [99]:
df

    b       c
a
1   4   kavan
2   5   krish
3  56   navin
4   6  dhynam
5   7   keval

In [103]:
df4['a'][0]

KeyError: 'a'

In [102]:
df['a'].median()

KeyError: 'a'

In [104]:
df11 = pd.DataFrame({"key1":[1,2,3,4,5,6],
                    "key2":[34,45,56,23,33,123],
                    "key3":[345,34,234,324,423,435]}
                   )

In [106]:
df11

   key1  key2  key3
0     1    34   345
1     2    45    34
2     3    56   234
3     4    23   324
4     5    33   423
5     6   123   435

In [111]:
df11.index['a','b','c','d','e','f']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [108]:
df11.set_index('a',inplace=True)

KeyError: "None of ['a'] are in the columns"

In [117]:
df11=pd.DataFrame(data,index = ['0','1','2','3','4'])

In [118]:
df11

   a   b       c
0  1   4   kavan
1  2   5   krish
2  3  56   navin
3  4   6  dhynam
4  5   7   keval

In [119]:
df11['a'].median()

3.0

In [120]:
df11['a'].mean()

3.0

In [121]:
df11['a'].mode()

0    1
1    2
2    3
3    4
4    5
Name: a, dtype: int64

In [123]:
df11['a'].std()

1.5811388300841898

In [124]:
df11['a'].sum()

15

In [125]:
df11['a'].min()

1

In [126]:
df11['a'].max()

5

In [127]:
df11['a'].var()

2.5

In [140]:
df12=pd.DataFrame({'a':[3,4,5,2,1,3,4,5,6]})

In [145]:
df12['a'].rolling(window =1).mean()

0    3.0
1    4.0
2    5.0
3    2.0
4    1.0
5    3.0
6    4.0
7    5.0
8    6.0
Name: a, dtype: float64

In [146]:
df12['a'].rolling(window =2).mean()

0    NaN
1    3.5
2    4.5
3    3.5
4    1.5
5    2.0
6    3.5
7    4.5
8    5.5
Name: a, dtype: float64

In [147]:
df12['a'].rolling(window =3).mean()

0         NaN
1         NaN
2    4.000000
3    3.666667
4    2.666667
5    2.000000
6    2.666667
7    4.000000
8    5.000000
Name: a, dtype: float64

In [149]:
df12

   a
0  3
1  4
2  5
3  2
4  1
5  3
6  4
7  5
8  6

In [150]:
df11['a'].cumsum()

0     1
1     3
2     6
3    10
4    15
Name: a, dtype: int64

In [152]:
#python pandas = Date  Functionality
date=pd.date_range(start = '2023-04-23',end = '2023-06-23')

In [153]:
date

DatetimeIndex(['2023-04-23', '2023-04-24', '2023-04-25', '2023-04-26',
               '2023-04-27', '2023-04-28', '2023-04-29', '2023-04-30',
               '2023-05-01', '2023-05-02', '2023-05-03', '2023-05-04',
               '2023-05-05', '2023-05-06', '2023-05-07', '2023-05-08',
               '2023-05-09', '2023-05-10', '2023-05-11', '2023-05-12',
               '2023-05-13', '2023-05-14', '2023-05-15', '2023-05-16',
               '2023-05-17', '2023-05-18', '2023-05-19', '2023-05-20',
               '2023-05-21', '2023-05-22', '2023-05-23', '2023-05-24',
               '2023-05-25', '2023-05-26', '2023-05-27', '2023-05-28',
               '2023-05-29', '2023-05-30', '2023-05-31', '2023-06-01',
               '2023-06-02', '2023-06-03', '2023-06-04', '2023-06-05',
               '2023-06-06', '2023-06-07', '2023-06-08', '2023-06-09',
               '2023-06-10', '2023-06-11', '2023-06-12', '2023-06-13',
               '2023-06-14', '2023-06-15', '2023-06-16', '2023-06-17',
               '2023-06-18', '2023-06-19', '2023-06-20', '2023-06-21',
               '2023-06-22', '2023-06-23'],
              dtype='datetime64[ns]', freq='D')

In [156]:
df_date = pd.DataFrame({'date':date})

In [155]:
df_date

         Date
0  2023-04-23
1  2023-04-24
2  2023-04-25
3  2023-04-26
4  2023-04-27
..        ...
57 2023-06-19
58 2023-06-20
59 2023-06-21
60 2023-06-22
61 2023-06-23

[62 rows x 1 columns]