In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("titanic.csv")

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.drop('PaddengerId')

KeyError: "['PaddengerId'] not found in axis"

In [9]:
df.drop('PassengerId',axis=1)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [10]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df=df.drop('PassangerId',axis=1)

In [12]:
"""this is above code for permonunt drop one column"""

'this is above code for permonunt drop one column'

In [14]:
df.drop('PassengerId',axis=1,inplace=True)

In [15]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [16]:
df.drop(3)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [18]:
df=df.drop(3)

In [19]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [20]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [21]:
 df.set_index("Name")

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [22]:
"""permanant changes name ko index banna hainpermannatly to niche code kiya hain """

'permanant changes name ko index banna hainpermannatly to niche code kiya hain '

In [23]:
df.set_index("Name",inplace=True)

In [24]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [25]:
df.reset_index()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
885,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
889,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [29]:
d={
    'key1':[3,4,5,6],
    'key2':[6,7,8,9],
    'key3':[7,8,9,10]
}

In [30]:
pd.DataFrame(d)

   key1  key2  key3
0     3     6     7
1     4     7     8
2     5     8     9
3     6     9    10

In [33]:
 df1=pd.read_csv("taxonomy.csv")

In [34]:
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [35]:
df1.dropna()

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [36]:
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [37]:
df1.dropna(inplace=True)

In [38]:
df1

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [39]:
df1.dropna(axis=1)

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [40]:
df2=read_csv("taxonomy.csv")

NameError: name 'read_csv' is not defined

In [1]:
import pandas as pd

In [2]:
pd.read_csv("./titanic.csv")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df=pd.read_csv("./titanic.csv")

In [5]:
df6=df[['Name', 'Survived','Pclass']][5:10]

In [6]:
df5=df[['Name','Survived','Pclass']][0:5]

In [7]:
df5

                                                Name  Survived  Pclass
0                            Braund, Mr. Owen Harris         0       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1       1
2                             Heikkinen, Miss. Laina         1       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1       1
4                           Allen, Mr. William Henry         0       3

In [8]:
df6

                                                Name  Survived  Pclass
5                                   Moran, Mr. James         0       3
6                            McCarthy, Mr. Timothy J         0       1
7                     Palsson, Master. Gosta Leonard         0       3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1       3
9                Nasser, Mrs. Nicholas (Adele Achem)         1       2

In [10]:
pd.concat([df5,df6])

                                                Name  Survived  Pclass
0                            Braund, Mr. Owen Harris         0       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1       1
2                             Heikkinen, Miss. Laina         1       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1       1
4                           Allen, Mr. William Henry         0       3
5                                   Moran, Mr. James         0       3
6                            McCarthy, Mr. Timothy J         0       1
7                     Palsson, Master. Gosta Leonard         0       3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1       3
9                Nasser, Mrs. Nicholas (Adele Achem)         1       2

In [13]:
df7=pd.concat([df5,df6],axis=1)

In [14]:
df7.fillna('kavan')

,Name,Survived,Pclass,Name,Survived,Pclass
0,"Braund, Mr. Owen Harris",0.0,3.0,kavan,kavan,kavan
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1.0,1.0,kavan,kavan,kavan
2,"Heikkinen, Miss. Laina",1.0,3.0,kavan,kavan,kavan
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1.0,1.0,kavan,kavan,kavan
4,"Allen, Mr. William Henry",0.0,3.0,kavan,kavan,kavan
5,kavan,kavan,kavan,"Moran, Mr. James",0.0,3.0
6,kavan,kavan,kavan,"McCarthy, Mr. Timothy J",0.0,1.0
7,kavan,kavan,kavan,"Palsson, Master. Gosta Leonard",0.0,3.0
8,kavan,kavan,kavan,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1.0,3.0
9,kavan,kavan,kavan,"Nasser, Mrs. Nicholas (Adele Achem)",1.0,2.0

In [15]:
data1 = pd.DataFrame({'key1':[1,2,3,4,5,6],
                     'key2':[4,5,6,7,8,9],
                     'key3':[3,4,5,65,6,45]})

In [16]:
data1

   key1  key2  key3
0     1     4     3
1     2     5     4
2     3     6     5
3     4     7    65
4     5     8     6
5     6     9    45

In [18]:
data2 = pd.DataFrame({'key3' : [1,2,3,4,5],
                     'key4': [4,5,6,7,8],
                     'key5': [6,7,8,12,4]})

In [19]:
data2

   key3  key4  key5
0     1     4     6
1     2     5     7
2     3     6     8
3     4     7    12
4     5     8     4

In [20]:
pd.merge(data1,data2)

   key1  key2  key3  key4  key5
0     1     4     3     6     8
1     2     5     4     7    12
2     3     6     5     8     4

In [21]:
"""yaha par inner merge operation perform hoga"""

'yaha par inner merge operation perform hoga'

In [22]:
pd.merge(data1,data2,how="left")

   key1  key2  key3  key4  key5
0     1     4     3   6.0   8.0
1     2     5     4   7.0  12.0
2     3     6     5   8.0   4.0
3     4     7    65   NaN   NaN
4     5     8     6   NaN   NaN
5     6     9    45   NaN   NaN

In [23]:
"""yaha par jo pehle aya wo left aajayega baad vala right rahega"""

'yaha par jo pehle aya wo left aajayega baad vala right rahega'

In [24]:
pd.merge(data1,data2,how='right')

   key1  key2  key3  key4  key5
0   NaN   NaN     1     4     6
1   NaN   NaN     2     5     7
2   1.0   4.0     3     6     8
3   2.0   5.0     4     7    12
4   3.0   6.0     5     8     4

In [25]:
"""yaha par same left ka ulta perform hoga """

'yaha par same left ka ulta perform hoga '

In [26]:
pd.merge(data1,data2,how='cross')

    key1  key2  key3_x  key3_y  key4  key5
0      1     4       3       1     4     6
1      1     4       3       2     5     7
2      1     4       3       3     6     8
3      1     4       3       4     7    12
4      1     4       3       5     8     4
5      2     5       4       1     4     6
6      2     5       4       2     5     7
7      2     5       4       3     6     8
8      2     5       4       4     7    12
9      2     5       4       5     8     4
10     3     6       5       1     4     6
11     3     6       5       2     5     7
12     3     6       5       3     6     8
13     3     6       5       4     7    12
14     3     6       5       5     8     4
15     4     7      65       1     4     6
16     4     7      65       2     5     7
17     4     7      65       3     6     8
18     4     7      65       4     7    12
19     4     7      65       5     8     4
20     5     8       6       1     4     6
21     5     8       6       2     5     7
22     5     8       6       3     6     8
23     5     8       6       4     7    12
24     5     8       6       5     8     4
25     6     9      45       1     4     6
26     6     9      45       2     5     7
27     6     9      45       3     6     8
28     6     9      45       4     7    12
29     6     9      45       5     8     4

In [27]:
"""sabko sabse multiply karega kartejian product aayega """

'sabko sabse multiply karega kartejian product aayega '

In [28]:
data1

   key1  key2  key3
0     1     4     3
1     2     5     4
2     3     6     5
3     4     7    65
4     5     8     6
5     6     9    45

In [30]:
data2

   key3  key4  key5
0     1     4     6
1     2     5     7
2     3     6     8
3     4     7    12
4     5     8     4

In [31]:
pd.merge(data1,data2,how='inner')

   key1  key2  key3  key4  key5
0     1     4     3     6     8
1     2     5     4     7    12
2     3     6     5     8     4

In [32]:
pd.merge(data1,data2,how='outer')

   key1  key2  key3  key4  key5
0   1.0   4.0     3   6.0   8.0
1   2.0   5.0     4   7.0  12.0
2   3.0   6.0     5   8.0   4.0
3   4.0   7.0    65   NaN   NaN
4   5.0   8.0     6   NaN   NaN
5   6.0   9.0    45   NaN   NaN
6   NaN   NaN     1   4.0   6.0
7   NaN   NaN     2   5.0   7.0

In [33]:
pd.merge(data1,data2,how='outer',on='key1')

KeyError: 'key1'

In [39]:
data1 = pd.DataFrame({'key1':[1,2,3,4,5,6],
                     'key2':[4,5,6,7,8,9],
                     'key3':[3,4,5,65,6,45]},
                     index = ['a','b','c','d','e','f']
                     
                     )

In [45]:
data2 = pd.DataFrame({'key11' : [1,2,3,4,5],
                     'key12': [4,5,6,7,8],
                     'key13': [6,7,8,12,4]},
                    index = ['g','h','i','j','k'])

In [40]:
data1

   key1  key2  key3
a     1     4     3
b     2     5     4
c     3     6     5
d     4     7    65
e     5     8     6
f     6     9    45

In [46]:
data2

   key11  key12  key13
g      1      4      6
h      2      5      7
i      3      6      8
j      4      7     12
k      5      8      4

In [47]:
data1.join(data2)

   key1  key2  key3  key11  key12  key13
a     1     4     3    NaN    NaN    NaN
b     2     5     4    NaN    NaN    NaN
c     3     6     5    NaN    NaN    NaN
d     4     7    65    NaN    NaN    NaN
e     5     8     6    NaN    NaN    NaN
f     6     9    45    NaN    NaN    NaN

In [48]:
data1.join(data2,how='right')

   key1  key2  key3  key11  key12  key13
g   NaN   NaN   NaN      1      4      6
h   NaN   NaN   NaN      2      5      7
i   NaN   NaN   NaN      3      6      8
j   NaN   NaN   NaN      4      7     12
k   NaN   NaN   NaN      5      8      4

In [50]:
data1.join(data2,how='left')

   key1  key2  key3  key11  key12  key13
a     1     4     3    NaN    NaN    NaN
b     2     5     4    NaN    NaN    NaN
c     3     6     5    NaN    NaN    NaN
d     4     7    65    NaN    NaN    NaN
e     5     8     6    NaN    NaN    NaN
f     6     9    45    NaN    NaN    NaN

In [51]:
data1.join(data2,how='outer')

   key1  key2  key3  key11  key12  key13
a   1.0   4.0   3.0    NaN    NaN    NaN
b   2.0   5.0   4.0    NaN    NaN    NaN
c   3.0   6.0   5.0    NaN    NaN    NaN
d   4.0   7.0  65.0    NaN    NaN    NaN
e   5.0   8.0   6.0    NaN    NaN    NaN
f   6.0   9.0  45.0    NaN    NaN    NaN
g   NaN   NaN   NaN    1.0    4.0    6.0
h   NaN   NaN   NaN    2.0    5.0    7.0
i   NaN   NaN   NaN    3.0    6.0    8.0
j   NaN   NaN   NaN    4.0    7.0   12.0
k   NaN   NaN   NaN    5.0    8.0    4.0

In [52]:
data1.join(data2,how='cross')

    key1  key2  key3  key11  key12  key13
0      1     4     3      1      4      6
1      1     4     3      2      5      7
2      1     4     3      3      6      8
3      1     4     3      4      7     12
4      1     4     3      5      8      4
5      2     5     4      1      4      6
6      2     5     4      2      5      7
7      2     5     4      3      6      8
8      2     5     4      4      7     12
9      2     5     4      5      8      4
10     3     6     5      1      4      6
11     3     6     5      2      5      7
12     3     6     5      3      6      8
13     3     6     5      4      7     12
14     3     6     5      5      8      4
15     4     7    65      1      4      6
16     4     7    65      2      5      7
17     4     7    65      3      6      8
18     4     7    65      4      7     12
19     4     7    65      5      8      4
20     5     8     6      1      4      6
21     5     8     6      2      5      7
22     5     8     6      3      6      8
23     5     8     6      4      7     12
24     5     8     6      5      8      4
25     6     9    45      1      4      6
26     6     9    45      2      5      7
27     6     9    45      3      6      8
28     6     9    45      4      7     12
29     6     9    45      5      8      4

In [53]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [54]:
df['Fare_INR']=df['Fare'].apply(lambda x: x*80)

In [55]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,580.000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,5702.664
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,634.000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4248.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,644.000

In [57]:
def eura_inr(x):
    return x*80

df['Fare_INR']=df['Fare'].apply(eura_inr)

In [58]:
df['Fare_INR']

0       580.000
1      5702.664
2       634.000
3      4248.000
4       644.000
         ...
886    1040.000
887    2400.000
888    1876.000
889    2400.000
890     620.000
Name: Fare_INR, Length: 891, dtype: float64

In [59]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,580.000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,5702.664
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,634.000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4248.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,644.000

In [60]:
df['name_len'] = df['Name'].apply(len)

In [61]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR,name_len
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,580.000,23
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,5702.664,51
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,634.000,22
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4248.000,44
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,644.000,24

In [62]:
def cat_fare(x):
    if x<10:
        return "cheap"
    elif x>=10 and x<20:
        return 'mid'
    else:
        return 'high'

In [64]:
df['cat_fair'] = df['Fare'].apply(cat_fare)