# ALgerian Forest Fires Dataset



About the data set

Date : (DD/MM/YYYY) Day, month ('june' to 'september'), year (2012)
Weather data observations

1.Temp : temperature noon (temperature max) in Celsius degrees: 22 to 42
2.RH : Relative Humidity in %: 21 to 90
3.Ws :Wind speed in km/h: 6 to 29
4.Rain: total day in mm: 0 to 16.8 FWI Components
5.Fine Fuel Moisture Code (FFMC) index from the FWI system: 28.6 to 92.5
6.Duff Moisture Code (DMC) index from the FWI system: 1.1 to 65.9
7.Drought Code (DC) index from the FWI system: 7 to 220.4
8.Initial Spread Index (ISI) index from the FWI system: 0 to 18.5
9.Buildup Index (BUI) index from the FWI system: 1.1 to 68
10.Fire Weather Index (FWI) Index: 0 to 31.1
11.Classes: two classes, namely:
      fire
      not Fire
Some facts about the data set

1.This dataset contains a culmination of forest fire observations and data in two regions of Algeria:
                          Bejaia region
                          Sidi Bel-Abbes region.
The Dataset contain data from June 2012 to September 2012.

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
dataset = pd.read_csv('Algerian_forest_fires_dataset.csv',header = 1)

In [3]:
dataset.head()

   1  6  2012  29  57  18     0  65.7  3.4   7.6  1.3 3.4.1  0.5  not fire
0  2  6  2012  29  61  13   1.3  64.4  4.1   7.6    1   3.9  0.4  not fire
1  3  6  2012  26  82  22  13.1  47.1  2.5   7.1  0.3   2.7  0.1  not fire
2  4  6  2012  25  89  13   2.5  28.6  1.3   6.9    0   1.7    0  not fire
3  5  6  2012  27  77  16     0  64.8    3  14.2  1.2   3.9  0.5  not fire
4  6  6  2012  31  67  14     0  82.6  5.8  22.2  3.1     7  2.5      fire

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   1            245 non-null    object
 1   6            244 non-null    object
 2   2012         244 non-null    object
 3   29           244 non-null    object
 4   57           244 non-null    object
 5   18           244 non-null    object
 6   0            244 non-null    object
 7   65.7         244 non-null    object
 8   3.4          244 non-null    object
 9   7.6          244 non-null    object
 10  1.3          244 non-null    object
 11  3.4.1        244 non-null    object
 12  0.5          244 non-null    object
 13  not fire     243 non-null    object
dtypes: object(14)
memory usage: 27.0+ KB

## Data Cleaning

In [5]:
## missing value 
dataset[dataset.isnull().any(axis = 1)]

,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4.1,0.5,not fire
121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,Sidi-Bel Abbes Region Dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,14,7,2012,37,37,18,0.2,88.9,12.9,14.6 9,12.5,10.4,fire,NaN

The Dataset is converted into two sets based on region from 122th index, we can make 
a new column based on the region 
1.:"Bejaia Region Dataset"
2.:"Sidi -Bel Abbes region Dataset"
add new column with region

In [12]:
dataset.loc[:122,"Region"]  = 0
dataset.loc[122:,"Region"] = 1
df=dataset

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   1            245 non-null    object
 1   6            244 non-null    object
 2   2012         244 non-null    object
 3   29           244 non-null    object
 4   57           244 non-null    object
 5   18           244 non-null    object
 6   0            244 non-null    object
 7   65.7         244 non-null    object
 8   3.4          244 non-null    object
 9   7.6          244 non-null    object
 10  1.3          244 non-null    object
 11  3.4.1        244 non-null    object
 12  0.5          244 non-null    object
 13  not fire     243 non-null    object
 14  Region       246 non-null    float64
 15  region       124 non-null    float64
dtypes: float64(2), object(14)
memory usage: 30.9+ KB

In [14]:
df[['Region']] =df[['Region']].astype(int)

In [15]:
df.head()

,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4.1,0.5,not fire,Region,region
0,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire,0,NaN
1,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0,NaN
2,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire,0,NaN
3,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire,0,NaN
4,6,6,2012,31,67,14,0,82.6,5.8,22.2,3.1,7,2.5,fire,0,NaN

In [17]:
df.tail()

,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4.1,0.5,not fire,Region,region
241,26,9,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire,1,1.0
242,27,9,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire,1,1.0
243,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire,1,1.0
244,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire,1,1.0
245,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire,1,1.0

In [18]:
df.isnull().sum()

1                1
6                2
2012             2
29               2
57               2
18               2
0                2
65.7             2
3.4              2
7.6              2
1.3              2
3.4.1            2
0.5              2
not fire         3
Region           0
region         122
dtype: int64

In [19]:
## Removing the null values 
df= df.dropna().reset_index(drop = True)

In [20]:
df.head()

,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4.1,0.5,not fire,Region,region
0,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,1,1.0
1,1,6,2012,32,71,12,0.7,57.1,2.5,8.2,0.6,2.8,0.2,not fire,1,1.0
2,2,6,2012,30,73,13,4,55.7,2.7,7.8,0.6,2.9,0.2,not fire,1,1.0
3,3,6,2012,29,80,14,2,48.7,2.2,7.6,0.3,2.6,0.1,not fire,1,1.0
4,4,6,2012,30,64,14,0,79.4,5.2,15.4,2.2,5.6,1,not fire,1,1.0

In [21]:
df.isnull().sum()

1              0
6              0
2012           0
29             0
57             0
18             0
0              0
65.7           0
3.4            0
7.6            0
1.3            0
3.4.1          0
0.5            0
not fire       0
Region         0
region         0
dtype: int64

In [26]:
df.iloc[[123]]

IndexError: positional indexers are out-of-bounds

In [27]:
## remove  the 122th row 
df= df.drop(123).reset_index(drop = True)

KeyError: '[123] not found in axis'